### ISSUE TITLE
QRコードを読んだら飛ぶページ

### ISSUE THREAD

**Issue by Ark-00** [Treasure-Hunting/Frontend#4]
QRコードをよんだら飛ぶページ
必要なもの：難易度確認ができるもの、２Iクラス展への誘導

**Comment by Snowman-s** [comment]
プレイヤさんとQRコードの難易度が同じで無かった時、それを伝える機能も必要ではないですか？

**Comment by Ark-00** [comment]
じゃあ、そのようにページ分割します。
必要なものを「合否によって、正解不正解を表示する枠」と、「次へ」ボタンに変更。

**Comment by raiga0310** [comment]
これ、/on-goal/に飛んだ時正解の場合は/last/に飛ぶから不正解の時のぺーじってことになるんですよね？

**Comment by raiga0310** [comment]
#13 で次へのボタンがいるかどうかの話ですが、Backendで/on-goal/に接続した場合、難易度が同じならリダイレクトして/last/に遷移するようにしてと思ううんですが、この判断で会ってますか  @Snowman-s @Siketyan

**Comment by siketyan** [comment]
存じ上げておりません．

**Comment by Snowman-s** [comment]
そうですね、あってます。このページ自体は不正解のページであります。

**Comment by raiga0310** [comment]
ありがとうございます
