### ISSUE TITLE
最終ページ

### ISSUE THREAD

**Issue by Ark-00** [Treasure-Hunting/Frontend#6]
最後にユーザーが到達するページ。
必要なもの：「２Iクラス展への誘導」「度の難易度をクリアしたかの表示」

**Comment by raiga0310** [comment]
プルリク通して概形は完成しました。
残りのページの概形等作ってからデザインは決めていきたいですね

**Comment by Snowman-s** [comment]
あ、「このページは閉じないでください」が必要だろうというのを忘れていた。
